### ISSUE TITLE
There is no way to navigate to metadata records for a thematic map

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#147] opened 2023-04-18 15:15 UTC
For example on a theme page: https://geo.ca/environment/

The featured map can be opened but I can't get to the metadata for the layer(s) to download or get more information about the data.

**Comment by sean-eagles** [comment] 2023-06-28 18:13
Duplicate of #185 , closing and redirecting to 185.

**Closed as completed by sean-eagles** 2023-06-28 18:13 UTC
Labels: bug-type: unexpected behavior, experience: ux
