### ISSUE TITLE
Link to metadata in featured layer cards on theme pages

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#185] opened 2023-06-15 16:41 UTC
Example: the following card should link to the layer/dataset metadata.
<img width="602" alt="Screen Shot 2023-06-15 at 9 34 34 AM" src="https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/2255248/c04b3fc1-d646-44d9-9b75-b9dbe6c7873d">

Link to:

<img width="1112" alt="Screen Shot 2023-06-15 at 9 37 45 AM" src="https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/2255248/89d5fa97-5024-4f4d-b5ab-9f0d183b910e">

**Comment by jaredkinger** [comment] 2023-06-21 19:26
@jvanulde Linking the title as well as adding a second link would be good. Having the link with an appropriate call to action adds context for the user clicking on the link.

Is this a duplicate of #147?

**Comment by jaredkinger** [comment] 2023-07-18 14:05
I've updated almost all of the featured layer cards to link the title to the metadata. However there are some cards that feature maps containing multiple metadata records. An example of this would be the [Administrative and Electoral Boundaries of Canada - 2019](https://geo.ca/wp-content/Viewer/config-int-ADMINISTRATION-iframe-map-en.html) that utilizes 3 different metadata records in the map layers. Should we be listing a link to each of the different metadata records used, choosing a main main data record to link to or something else altogether?

**Closed as completed** 2023-08-30 14:35 UTC
Labels: experience: ux, needs: ux review
