### ISSUE TITLE
Old page still indexed - dows not show up in WordPress.

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#96] opened 2022-12-07 21:01 UTC
view-source: https://www.geo.ca/weeklytravelspecials/

There is an old travel page still left over from the old domain owner it seems.

GEO.ca Language Selection - GEO.CA: https://www.geo.ca/weeklytravelspecials/)
GEO.ca Language Selection - GEO.CA: http://geo.ca/

When Jared comes in we can assign to him.

**Comment by jaredkinger** [comment] 2023-01-05 20:40
@sean-eagles Wanted to confirm I saw this. This should likely be 404'ing if the page doesn't exist in WordPress. It looks like it is attempting to redirect to the Language Selector splash but is showing up blank because of the relative URLs for assets being used are also 404'ing. I have a feeling this is related to #100. I'm just waiting to get access to WP and then I will confirm the fix.

Once the page properly starts to return a 404 it should de-index itself or we can look into manually de-indexing if necessary.

**Comment by elatsis** [comment] 2023-01-09 15:53
Will be resolved by #100

**Comment by elatsis** [comment] 2023-02-01 13:23
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/96?planning-poker) with Zenhub @sean-eagles @jaredkinger

**Comment by jaredkinger** [comment] 2023-02-01 20:37
This page is now correctly returning a 404. I am working on a more user friendly 404 page as part of #100

**Comment by pvautour** [comment] 2023-02-03 13:18
I can confirm, seems fixed by handling the 404 properly. We can close this.

**Closed as completed by pvautour** 2023-02-03 13:18 UTC
Labels: bug-type: confusing
