### ISSUE TITLE
Map thumbnail previews fail to load

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#130] opened 2023-02-17 04:42 UTC
On Safari browser in a theme page the maps on the right don't load. There is an error displayed on the bottom of the Emergency theme page as well:

"We're sorry, something went wrong, please refresh the page."

Where this error shows up there is no "Most accessed" panel rendered.

<img width="702" alt="Screen Shot 2023-02-16 at 8 34 33 PM" src="https://user-images.githubusercontent.com/2255248/219550906-dd91b472-dac5-49ea-8c81-8048c1a628ef.png">

Dev tools log:

'''
[Warning] m {message: "Unable to load https://geo.statcan.gc.ca/geo_wa/re…turnCountOnly=true&returnGeometry=false status: 0", stack: "m@https://js.arcgis.com/3.35/init.js:113:364↵D@https://js.arcgis.com/3.35/init.js:147:228", response: Object, status: 0, responseText: "", …} (rv-main.js, line 328)
[Warning] m {message: "Unable to load https://geo.statcan.gc.ca/geo_wa/re…turnCountOnly=true&returnGeometry=false status: 0", stack: "m@https://js.arcgis.com/3.35/init.js:113:364↵D@https://js.arcgis.com/3.35/init.js:147:228", response: Object, status: 0, responseText: "", …} (rv-main.js, line 328)
[Info] Successfully preconnected to https://fonts.gstatic.com/
[Log] JQMIGRATE: Migrate is installed, version 3.3.2 (jquery-migrate.min.js, line 2)
[Warning] 🚀 – "container.buildInfo.environment is deprecated.Please use `container.environment.stage` instead" (launch-f7c3e6060667.min.js, line 18)
[Warning] 🚀 – "container.buildInfo.environment is deprecated.Please use `container.environment.stage` instead" (launch-f7c3e6060667.min.js, line 18)
[Warning] 🚀 – "container.buildInfo.environment is deprecated.Please use `container.environment.stage` instead" (launch-f7c3e6060667.min.js, line 18)
[Warning] The RAMP viewers legacy API is deprecated and will be removed in a future release. (legacy-api.js, line 1)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (gcpv-main.js:200)
[Error] ReferenceError: Can't find variable: cgpv
	Global Code (emergency:981)
[Error] Failed to load resource: the server responded with a status of 404 () (KFOmCnqEu92Fr1Mu4mxK.woff2, line 0)
[Warning] pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details. (rv-main.js, line 79, x2)
[Error] Failed to load resource: the server responded with a status of 404 () (KFOlCnqEu92Fr1MmWUlfBBc4.woff2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (KFOlCnqEu92Fr1MmEU9fBBc4.woff2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (cgp-video-min.js.map, line 0)
[Warning] The plugin table was loaded automatically. This functionality may be removed in a future release. Please load this plugin on the host page instead (see ramp documentation) or add 'no-table' to rv-plugins to stop this plugin from being autoloaded. (rv-main.js, line 366, x2)
[Error] Cross-origin redirection to https://maps-cartes.services.geo.ca/server2_serveur2/rest/services/BaseMaps/CBMT3978/MapServer?f=json denied by Cross-Origin Resource Sharing policy: Origin https://geo.ca is not allowed by Access-Control-Allow-Origin. Status code: 301
[Error] XMLHttpRequest cannot load https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer?f=json due to access control checks.
[Error] Failed to load resource: Cross-origin redirection to https://maps-cartes.services.geo.ca/server2_serveur2/rest/services/BaseMaps/CBMT3978/MapServer?f=json denied by Cross-Origin Resource Sharing policy: Origin https://geo.ca is not allowed by Access-Control-Allow-Origin. Status code: 301 (MapServer, line 0)
[Error] Cross-origin redirection to https://maps-cartes.services.geo.ca/server2_serveur2/rest/services/BaseMaps/CBMT3978/MapServer?f=json denied by Cross-Origin Resource Sharing policy: Origin https://geo.ca is not allowed by Access-Control-Allow-Origin. Status code: 301
[Error] XMLHttpRequest cannot load https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer?f=json due to access control checks.
[Error] Failed to load resource: Cross-origin redirection to https://maps-cartes.services.geo.ca/server2_serveur2/rest/services/BaseMaps/CBMT3978/MapServer?f=json denied by Cross-Origin Resource Sharing policy: Origin https://geo.ca is not allowed by Access-Control-Allow-Origin. Status code: 301 (MapServer, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (KFOlCnqEu92Fr1MmSU5fBBc-.woff, line 0)
[Warning] focusManager – "*stopPropagation* is disabled on elements inside or part of the viewer" (rv-main.js, line 1243, x6)
[Warning] focusManager – "You cannot use *rvFocus* on elements that are outside the viewer" (rv-main.js, line 1243, x2)
[Warning] focusManager – "*stopPropagation* is disabled on elements inside or part of the viewer" (rv-main.js, line 1243, x8)
[Warning] focusManager – "You cannot use *rvFocus* on elements that are outside the viewer" (rv-main.js, line 1243, x2)
[Warning] focusManager – "*stopPropagation* is disabled on elements inside or part of the viewer" (rv-main.js, line 1243, x12)
'''

**Comment by jaredkinger** [comment] 2023-02-17 13:39
Seems like there is two different errors happening here.

"We're sorry, something went wrong, please refresh the page." It looked like the geocore api wasn't returning the expected data when I first view the page. However hitting the page now you should see "Most accessed emergency data" and then the 5 maps below it. Not sure why the API wasn't returning the proper data as it seems to have resolved itself unless Bo did something to fix that.

I checked the Emergency page in Safari and I am seeing the issue with the maps. This appears to be an issue on all theme pages in Safari. I double checked Chrome, Firefox and Edge and the issue is not present so this is browser specific. I will investigate.

**Comment by jaredkinger** [comment] 2023-02-17 17:31
The two important errors here are:

- [Error] SyntaxError: Invalid regular expression: invalid group specifier name (anonymous function) (gcpv-main.js:200)
- [Error] ReferenceError: Can't find variable: cgpv

The cgpv variable is declared in [gcpv-main.js](https://viewer-visualiseur.services.geo.ca/apps/GeoView/geoview-0.0.1/gcpv-main.js) and doesn't exist because of the syntax error. The syntax error is specific to the [regexp lookbehind](https://caniuse.com/js-regexp-lookbehind) which is not currently supported by Safari but does look like it may be supported in [Safari 16.4](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#JavaScript).

The javascript file above appears to be an older version of Geoview however the bug still exists in the newer version which you can see by loading this [demo](https://canadian-geospatial-platform.github.io/geoview/public/load-test.html) in Safari.

@jolevesq can you take a look at this?

**Comment by jaredkinger** [comment] 2023-02-17 19:09
Geocore API is intermittently returning the following error:
```
{
  "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}
```
This is causing the "We're sorry, something went wrong, please refresh the page." error message to be displayed.

**Comment by bo-lu** [comment] 2023-02-17 21:48
The geocore api issue should be fixed. Related: #131

**Closed as completed** 2023-05-29 14:37 UTC
Labels: problem: bug
